sudo: false

language:
  - python

python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then py.test -vv pytest-example.py --cov pytest-example;
    else py.test -vv pytest-example.py;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then coveralls;
    fi

notifications:
  email: false
